name: Build Push and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # ---------------- DOCKER ----------------

    - name: Docker login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build backend
      run: docker build --no-cache -t ajithkumarreddy/todo-backend:latest -f docker/Dockerfile .

    - name: Build frontend
      run: docker build --no-cache -t ajithkumarreddy/todo-frontend:latest -f docker/Dockerfile.frontend .

    - name: Push backend
      run: docker push ajithkumarreddy/todo-backend:latest

    - name: Push frontend
      run: docker push ajithkumarreddy/todo-frontend:latest


    # ---------------- KUBERNETES ----------------

    - name: Install kubectl
      uses: azure/setup-kubectl@v4

    - name: Configure kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
        chmod 600 $HOME/.kube/config

    # VERY IMPORTANT â†’ force kubectl to use this config
    - name: Verify cluster connection
      env:
        KUBECONFIG: $HOME/.kube/config
      run: kubectl get nodes

    - name: Restart deployments
      env:
        KUBECONFIG: $HOME/.kube/config
      run: |
        kubectl rollout restart deployment backend
        kubectl rollout restart deployment frontend
        kubectl rollout status deployment backend
        kubectl rollout status deployment frontend
